pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                dir('jenkinstarter') {
                    sh 'mvn -B clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir('jenkinstarter') {
                    sh 'mvn -B test'
                }
            }
            post {
                always {
                    junit 'jenkinstarter/target/test-reports/*.xml'
                }
            }
        }
        stage('Archive') {
            steps {
                archiveArtifacts artifacts: 'jenkinstarter/target/*.jar', fingerprint: true
            }
        }
    }
}
